name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./ https://parcial-electiva2.surge.sh --token $SURGE_TOKEN
